export enum StateType {
    NOSTATE = 'NOSTATE',
    UNKNOWN = 'UNKNOWN',
    PREINIT_TRAY_OPEN = 'PREINIT_TRAY_OPEN',
    IDLE = 'IDLE',
    BUSY = 'BUSY',
    BUSY_NOT_STOPABLE = 'BUSY_NOT_STOPABLE',
    ERROR = 'ERROR',
    SLEEP = 'SLEEP',
    POWEROFF = 'POWEROFF',
    TRAYOPEN = 'TRAYOPEN',
    INTRASITION = 'INTRASITION',
} 